policies:
  - name: "FallbackPolicy"
    nlu_threshold: 0.35
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
  - name: FormPolicy
  - name: KerasPolicy
    epochs: 50
    max_history: 6
  - name: MemoizationPolicy
    max_history: 6
